# run the evaluation of a robot controller and store the result in the participants.json file

name: Run Evaluation

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  evaluation:
    name: Evaluation Requested by a Participant
    runs-on: ubuntu-20.04
    steps:
      - name: Record Animation and Update Performance
        id: webots_test
        uses: cyberbotics/competition-record-action@enhancement-separate-inputs
        with:
          participant-repo-id: 12341234
          participant-repo-name: testest
          participant-repo-private: true
          log-url: https://zombo.com
          repo-token: 43214312
          allow-push: true
